import{i as l,S as c}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const u=document.querySelector(".form");document.querySelector(".search-btn");const i=document.querySelector(".gallery");u.addEventListener("submit",o=>{o.preventDefault();const r=o.target.elements.searchRequest.value.trim();if(r===""){l.show({class:"toast-message",message:"Fill search field please",messageColor:"#fff",backgroundColor:"#59A10D",border:"2px solid #B5EA7C",position:"topRight"});return}i.innerHTML='<span class="loader">Loading</span>',console.log(r),f(r).then(s=>g(s)).catch(s=>console.log(s))});function f(o){return fetch(d(o)).then(r=>{if(!r.ok)throw new Error(r.status);return console.log(r),r.json().hits})}function d(o){const r="https://pixabay.com/api/",s="46357253-cea0b9d68f62a9d404cc68056";let a="photo",e="horizontal",t=!0;const n=new URLSearchParams({key:s,q:o,image_type:a,orientation:e,safesearch:t});return`${r}?${n}`}function g(o){if(console.log(o),o.length===0){l.show({class:"toast-message",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",iconUrl:"img/error-icon.svg",iconColor:"#fff",backgroundColor:"#EF4040",border:"2px solid #FFBEBE",position:"topRight"});return}const r=o.reduce((s,a)=>`${s}
        <li class="gallery-item">
            <a class="gallery-link" href="${a.largeImageURL}">
                <img 
                class="gallery-image"
                src="${a.webformatURL}"
                alt="${a.tags}"
                />
            </a>
        </li>`,"");i.innerHTML=r,new c(".gallery-link",{captionsData:"alt",overlayOpacity:.5})}
//# sourceMappingURL=index.js.map
